import { sqliteTable, text, integer, real, index } from "drizzle-orm/sqlite-core";
import {
  pgTable,
  text as pgText,
  integer as pgInteger,
  doublePrecision,
  jsonb,
  varchar,
  index as pgIndex,
} from "drizzle-orm/pg-core";

// ── SQLite schema ──────────────────────────────────────────────────────

export const modelInvocationLogsSqlite = sqliteTable("model_invocation_logs", {
  id: text("id").primaryKey(),
  projectId: text("project_id"),
  orgId: text("org_id"),
  runId: text("run_id"),
  sessionId: text("session_id"),
  turnId: text("turn_id"),
  agentName: text("agent_name"),
  externalUser: text("external_user"),
  mode: text("mode").notNull(),
  operation: text("operation").notNull(),
  requestedProvider: text("requested_provider"),
  requestedModel: text("requested_model").notNull(),
  resolvedProvider: text("resolved_provider"),
  resolvedModel: text("resolved_model"),
  finalProvider: text("final_provider"),
  attemptIndex: integer("attempt_index"),
  attemptCount: integer("attempt_count"),
  generationId: text("generation_id"),
  credentialType: text("credential_type"),
  status: text("status").notNull(),
  errorClass: text("error_class"),
  errorMessage: text("error_message"),
  inputTokens: integer("input_tokens"),
  outputTokens: integer("output_tokens"),
  reasoningTokens: integer("reasoning_tokens"),
  cachedTokens: integer("cached_tokens"),
  audioInputSeconds: real("audio_input_seconds"),
  audioOutputSeconds: real("audio_output_seconds"),
  imageCount: integer("image_count"),
  videoSeconds: real("video_seconds"),
  estimatedCostUsd: real("estimated_cost_usd"),
  billableCostUsd: real("billable_cost_usd"),
  costSource: text("cost_source").notNull().default("unknown"),
  billingOwner: text("billing_owner").notNull().default("external"),
  rawMetadata: text("raw_metadata"),
  createdAt: text("created_at").notNull(),
}, (table) => [
  index("idx_model_invocations_project_created").on(table.projectId, table.createdAt),
  index("idx_model_invocations_org_created").on(table.orgId, table.createdAt),
  index("idx_model_invocations_run").on(table.runId),
  index("idx_model_invocations_session").on(table.sessionId),
  index("idx_model_invocations_agent").on(table.agentName),
]);

// ── PostgreSQL schema ──────────────────────────────────────────────────

export const modelInvocationLogsPg = pgTable("model_invocation_logs", {
  id: pgText("id").primaryKey(),
  projectId: pgText("project_id"),
  orgId: pgText("org_id"),
  runId: pgText("run_id"),
  sessionId: pgText("session_id"),
  turnId: pgText("turn_id"),
  agentName: pgText("agent_name"),
  externalUser: pgText("external_user"),
  mode: pgText("mode").notNull(),
  operation: pgText("operation").notNull(),
  requestedProvider: pgText("requested_provider"),
  requestedModel: pgText("requested_model").notNull(),
  resolvedProvider: pgText("resolved_provider"),
  resolvedModel: pgText("resolved_model"),
  finalProvider: pgText("final_provider"),
  attemptIndex: pgInteger("attempt_index"),
  attemptCount: pgInteger("attempt_count"),
  generationId: pgText("generation_id"),
  credentialType: pgText("credential_type"),
  status: varchar("status", { length: 32 }).notNull(),
  errorClass: pgText("error_class"),
  errorMessage: pgText("error_message"),
  inputTokens: pgInteger("input_tokens"),
  outputTokens: pgInteger("output_tokens"),
  reasoningTokens: pgInteger("reasoning_tokens"),
  cachedTokens: pgInteger("cached_tokens"),
  audioInputSeconds: doublePrecision("audio_input_seconds"),
  audioOutputSeconds: doublePrecision("audio_output_seconds"),
  imageCount: pgInteger("image_count"),
  videoSeconds: doublePrecision("video_seconds"),
  estimatedCostUsd: doublePrecision("estimated_cost_usd"),
  billableCostUsd: doublePrecision("billable_cost_usd"),
  costSource: pgText("cost_source").notNull().default("unknown"),
  billingOwner: pgText("billing_owner").notNull().default("external"),
  rawMetadata: jsonb("raw_metadata"),
  createdAt: pgText("created_at").notNull(),
}, (table) => [
  pgIndex("idx_pg_model_invocations_project_created").on(table.projectId, table.createdAt),
  pgIndex("idx_pg_model_invocations_org_created").on(table.orgId, table.createdAt),
  pgIndex("idx_pg_model_invocations_run").on(table.runId),
  pgIndex("idx_pg_model_invocations_session").on(table.sessionId),
  pgIndex("idx_pg_model_invocations_agent").on(table.agentName),
]);
