export { DashboardProvider, useDashboardHost, useDashboardHref } from "./host.js";
export type { DashboardCapabilities, DashboardHost } from "./host.js";
export { PageBody, PageHeader, Button, IconButton, DataTable, LoadingRows } from "./components.js";
export type { ColumnMeta } from "./components.js";
export { PageBody as V2PageBody, PageHeader as V2PageHeader } from "./v2/ui/page-header.js";
export { Button as V2Button } from "./v2/ui/button.js";
export { DataTable as V2DataTable } from "./v2/ui/data-table.js";
export { RefreshButton as V2RefreshButton } from "./v2/ui/refresh-button.js";
export { DashboardShell } from "./v2/shell/dashboard-shell.js";
export { AgentsTable as V2AgentsView } from "./v2/views/agents.js";
export { SelfHostAgentDetailView as V2AgentDetailView } from "./v2/agents/self-host-detail.js";
export { SkillsCatalog as V2SkillsView } from "./v2/views/skills.js";
export { SelfHostSkillDetailView as V2SkillDetailView } from "./v2/skills/self-host-detail.js";
export { FilesView as V2FilesView } from "./v2/views/files.js";
export { MemoryView as V2MemoryView } from "./v2/views/memory.js";
export { SelfHostSessionsView as V2SessionsView, SelfHostSessionDetailView as V2SessionDetailView } from "./v2/sessions/self-host.js";
export { SelfHostPlaygroundView as V2PlaygroundView } from "./v2/playground/self-host.js";
export { SelfHostToolsView as V2ToolsView, SelfHostToolDetailView as V2ToolDetailView } from "./v2/tools/self-host.js";
export { AgentsView } from "./views/agents.js";
export { AgentDetailView } from "./views/agent-detail.js";
export { PlaygroundView } from "./views/playground.js";
export { SessionsView } from "./views/sessions.js";
export { SessionDetailView } from "./views/session-detail.js";
export { MemoryView } from "./views/memory.js";
export { SkillsView } from "./views/skills.js";
export { FilesView } from "./views/files.js";
