// ── Client ────────────────────────────────────────────────────
export { PolpoClient, ChatCompletionStream } from "./client/polpo-client.js";
export type { PolpoClientConfig } from "./client/polpo-client.js";
export { EventSourceManager } from "./client/event-source.js";
export type { ConnectionStatus, EventSourceConfig } from "./client/event-source.js";
export { PolpoApiError } from "./client/errors.js";

// ── Store ─────────────────────────────────────────────────────
export { PolpoStore } from "./store/polpo-store.js";
export { reduceEvent } from "./store/event-reducer.js";
export {
  selectTasks,
  selectTask,
  selectMissions,
  selectMission,
  selectMissionReport,
  selectProcesses,
  selectEvents,
  selectAssessmentProgress,
  selectAssessmentChecks,
} from "./store/selectors.js";

// ── Types ─────────────────────────────────────────────────────
export type {
  Task,
  TaskStatus,
  TaskResult,
  TaskExpectation,
  TaskPhase,
  TaskOutcome,
  ExpectedOutcome,
  OutcomeType,
  Mission,
  MissionStatus,
  MissionReport,
  MissionDelay,
  AgentConfig,
  AgentIdentity,
  AgentResponsibility,
  AgentProcess,
  AgentActivity,
  Team,
  AssessmentResult,
  AssessmentTrigger,
  DimensionScore,
  DimensionScoreEvidence,
  EvalDimension,
  CheckResult,
  ReviewerResult,
  ReviewerMessage,
  ReviewerExploration,
  MetricResult,
  PolpoState,
  PolpoConfig,
  PolpoSettings,
  ReasoningLevel,
  ModelConfig,
  ModelAllowlistEntry,
  CustomModelDef,
  ProviderConfig,
  SSEEvent,
  ActiveDelay,
  CreateTaskRequest,
  UpdateTaskRequest,
  CreateMissionRequest,
  UpdateMissionRequest,
  AddMissionTaskRequest,
  UpdateMissionTaskRequest,
  ReorderMissionTasksRequest,
  AddMissionCheckpointRequest,
  UpdateMissionCheckpointRequest,
  AddMissionDelayRequest,
  UpdateMissionDelayRequest,
  AddMissionQualityGateRequest,
  UpdateMissionQualityGateRequest,
  AddMissionTeamMemberRequest,
  UpdateMissionTeamMemberRequest,
  UpdateMissionNotificationsRequest,
  ExecuteMissionResult,
  ResumeMissionResult,
  AddAgentRequest,
  UpdateAgentRequest,
  UpdateSettingsRequest,
  AddTeamRequest,
  TaskFilters,
  LogSession,
  LogEntry,
  RunActivityEntry,
  ChatSession,
  ChatMessage,
  ChatCompletionMessage,
  TextContentPart,
  ImageUrlContentPart,
  ContentPart,
  ChatCompletionRequest,
  ChatCompletionResponse,
  ChatCompletionChoice,
  ChatCompletionChunk,
  ChatCompletionChunkDelta,
  ToolCallState,
  ToolCallEvent,
  AskUserOption,
  AskUserQuestion,
  AskUserPayload,
  AskUserAnswer,
  MissionPreviewPayload,
  VaultEntryMeta,
  VaultPreviewPayload,
  AuthProfileStatus,
  AuthProfileType,
  AuthProfileMeta,
  ProviderAuthInfo,
  AuthStatusResponse,
  SkillInfo,
  LoadedSkill,
  SkillWithAssignment,
  SkillIndexEntry,
  SkillIndex,
  NotificationChannelType,
  NotificationChannelConfig,
  ChannelGatewayConfig,
  DmPolicy,
  NotificationRule,
  NotificationRecord,
  NotificationStats,
  NotificationSeverity,
  NotificationStatus,
  ScopedNotificationRules,
  SendNotificationRequest,
  SendNotificationResult,
  ApprovalRequest,
  ApprovalStatus,
  ScheduleEntry,
  CreateScheduleRequest,
  UpdateScheduleRequest,
  QualityMetrics,
  PlaybookParameter,
  PlaybookInfo,
  PlaybookDefinition,
  PlaybookRunResult,
  CreatePlaybookRequest,
  CreateSkillRequest,
  InstallSkillsResult,
  InstallSkillsOptions,
  TemplateParameter,
  TemplateInfo,
  TemplateDefinition,
  TemplateRunResult,
  Attachment,
  FileRoot,
  FileEntry,
  FilePreview,
} from "./client/types.js";

export type { StoreState, PolpoStats, AssessmentProgressEntry, AssessmentCheckStatus } from "./store/types.js";
export type { TaskFilter } from "./store/selectors.js";
